"""
Tests for scenario registry functions.

Tests bug fixes and correct behavior of registry functions.
"""

import pytest
from fos.core.scenarios.registry import get_all_scenarios, ALL_SCENARIOS


class TestScenarioRegistry:
    """Test scenario registry functions."""

    def test_get_all_scenarios_does_not_mutate_original(self):
        """Calling get_all_scenarios() should not mutate ALL_SCENARIOS."""
        # Find a sociology scenario before calling get_all_scenarios
        sociology_scenario = None
        for scenario in ALL_SCENARIOS:
            if scenario.get("category_actions") == "sociology":
                sociology_scenario = scenario
                break

        if sociology_scenario is None:
            pytest.skip("No sociology scenarios found")

        # Record the original type
        original_type = type(sociology_scenario["category_actions"]).__name__
        assert original_type == "str", f"Expected str, got {original_type}"

        # Call get_all_scenarios - this might mutate if bug exists
        _ = get_all_scenarios()

        # Check that the original scenario wasn't mutated
        after_type = type(sociology_scenario["category_actions"]).__name__
        assert after_type == "str", \
            f"Scenario was mutated from str to {after_type}!"


class TestPolicyMeaningErosionRegistration:
    """Policy Meaning Erosion is the visible template for cascade runtime."""

    def test_policy_erosion_is_visible_once(self):
        """Only policy_erosion should be shown to users for this workflow."""
        ids = [s["id"] for s in ALL_SCENARIOS]
        assert ids.count("policy_erosion") == 1
        assert "policy_cascade_experiment" not in ids

    def test_scenario_has_required_fields(self):
        """Scenario entry must have id, name, category, and description."""
        scenario = next(s for s in ALL_SCENARIOS if s["id"] == "policy_erosion")
        assert scenario["name"]
        assert scenario["category"]
        assert scenario["description"]

    def test_scene_key_exists_in_scene_map(self):
        """The dedicated policy cascade runtime must remain registered."""
        from fos.core.registry import SCENE_MAP

        assert "policy_cascade_scene" in SCENE_MAP

    def test_scenario_has_cascade_parameters(self):
        """Policy erosion should expose the cascade runtime parameters."""
        scenario = next(s for s in ALL_SCENARIOS if s["id"] == "policy_erosion")
        param_keys = [p["key"] for p in scenario.get("parameters", [])]
        assert "cascade_mode" in param_keys
        assert "distortion_strength" in param_keys
        assert "conflict_sensitivity" in param_keys
        assert "block_probability" in param_keys


class TestCoordinationGameScenario:
    """Test Coordination Game scenario structure."""

    def test_coordination_game_has_no_graph_generation_params(self):
        """COORDINATION_GAME should not have graph_type or edge_probability params.

        Graphs are created in the frontend via NetworkEditorModal, not generated by the backend.
        """
        from fos.core.scenarios.registry import COORDINATION_GAME

        param_ids = [p["id"] for p in COORDINATION_GAME.get("parameters", [])]

        assert "graph_type" not in param_ids, \
            "graph_type should be removed - graphs come from frontend"
        assert "edge_probability" not in param_ids, \
            "edge_probability should be removed - graphs come from frontend"

    def test_coordination_game_has_configurable_choices(self):
        """COORDINATION_GAME should allow users to configure the choices."""
        from fos.core.scenarios.registry import COORDINATION_GAME

        param_ids = [p["id"] for p in COORDINATION_GAME.get("parameters", [])]

        assert "choices" in param_ids, \
            "COORDINATION_GAME should have a 'choices' parameter for configuring options"

    def test_coordination_game_has_goal_parameter(self):
        """COORDINATION_GAME should have a goal parameter (match/differ)."""
        from fos.core.scenarios.registry import COORDINATION_GAME

        param_ids = [p["id"] for p in COORDINATION_GAME.get("parameters", [])]

        assert "goal" in param_ids, \
            "COORDINATION_GAME should have a 'goal' parameter"
